### ISSUE TITLE
Remove obsolete files / tests from V2 branch...

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/repy_v2#67]
There are a lot of obsolete files in the V2 branch.   They should be removed.

I'll put a list of files here which I think should go....

**Comment by aaaaalbert** [comment]
Here is my triage of the things mentioned in the comments above. Keep in mind that the comments relate to a much earlier state of this repository.

* `shims` have been replaced by Affix, and are not an integral part of RepyV2 anyway.
* `nodemanager`, `portability` `seattlelib`, Repy version 1 and its apps, `resource`, `softwareupdater` are now in separate repos as well.
* Many of the test file names mentioned are not valid for SeattleTestbed/utf, and have been ported to use this framework in their respective repos, or removed.

Further cleanup of unit tests that *are* relevant to RepyV2 is provided in #140, including file renames so that Repy-based tests bear the correct file extension, `.r2py`.
